# Generated by Django 6.0.4 on 2026-04-29 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivationalQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('author', models.CharField(max_length=150)),
                ('source', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AdminMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='#F97316', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('task_type', models.CharField(choices=[('individual', '👤 Individual'), ('colaborativo', '👥 Colaborativo')], default='individual', max_length=15)),
                ('deadline', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('penalty_applied_days', models.IntegerField(default=0)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='core.folder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=0)),
                ('streak', models.IntegerField(default=0)),
                ('league', models.CharField(choices=[('papel', '📄 Papel'), ('carton', '📦 Cartón'), ('madera', '🪵 Madera'), ('cobre', '🟤 Cobre'), ('bronce', '🥉 Bronce'), ('aluminio', '⚙️ Aluminio'), ('plata', '🥈 Plata'), ('oro', '🥇 Oro'), ('esmeralda', '💚 Esmeralda'), ('cuarzo', '🔮 Cuarzo'), ('onix', '🖤 Ónix'), ('amatista', '💜 Amatista'), ('diamante', '💎 Diamante'), ('obsidiana', '🌑 Obsidiana')], default='papel', max_length=20)),
                ('rank', models.CharField(choices=[('aprendiz', '📖 Aprendiz'), ('estudioso', '📚 Estudioso'), ('erudito', '🧐 Erudito'), ('scholar', '🎓 Scholar'), ('investigador', '🔬 Investigador'), ('prodigio', '⚡ Prodigio'), ('academico', '🏛️ Académico'), ('cientifico', '⚗️ Científico'), ('filosofo', '🦉 Filósofo'), ('sabio', '🌟 Sabio'), ('maestro', '🎯 Maestro'), ('visionario', '🔭 Visionario'), ('genio', '💡 Genio'), ('iluminado', '✨ Iluminado'), ('leyenda', '🏆 Leyenda')], default='aprendiz', max_length=20)),
                ('last_login_date', models.DateField(blank=True, null=True)),
                ('avatar_initial', models.CharField(default='', max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
